### ISSUE TITLE
prepare_dual_topology.py --config_file=step2.ini  issues

### ISSUE THREAD

**Issue by wenzeyu126553** [luancarvalhomartins/PyAutoFEP#139]
(FEP) zhyx@zhyx:~/PyAutoFEP$ prepare_dual_topology.py --config_file=step2.ini --output_hidden_temp_dir=False
=============== mdp and run steps=================
         Complex                    Water          
        min01.mdp                 min01.mdp        
        min02.mdp                 min02.mdp        
        min03.mdp                  nve.mdp         
         nve.mdp                   nvt.mdp         
         nvt.mdp                   npt.mdp         
         npt.mdp                   md.mdp          
         md.mdp                       -            
==================================================
================= Input ligands ==================
   Name         Molecule            Topology      
  FXR_12   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c(Cl)c1[H] lig_data/FXR_12.itp
  FXR_74   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c(Br)c1[H] lig_data/FXR_74.itp
  FXR_76   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c([H])c1[H] lig_data/FXR_76.itp
  FXR_84   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c(F)c1[H] lig_data/FXR_84.itp
  FXR_85   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c(C([H])([H])[H])c1[H] lig_data/FXR_85.itp
  FXR_88   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c(C(F)(F)F)c1[H] lig_data/FXR_88.itp
==================================================
================= Perturbations ==================
         State A                  State B         
         FXR_12                   FXR_74          
         FXR_12                   FXR_76          
         FXR_12                   FXR_84          
         FXR_12                   FXR_85          
         FXR_12                   FXR_88          
==================================================
=================== Poses read ===================
Name            File                 Details             
FXR_12          {'molecule': <rdkit.Chem.PropertyMol.PropertyMol object at 0x148eb217ba90>, 'topology': ['lig_data/FXR_12.itp']}                   
=============== Superimposed poses ===============
Name            File                      Note           
FXR_12          {'molecule': <rdkit.Chem.PropertyMol.PropertyMol object at 0x148eb217ba90>, 'topology': ['lig_data/FXR_12.itp']} Read from saved state
==================================================
================== Align poses ===================
Molecule FXR_12 aligned
================ Working on pairs ================
Perturbation Pose Coordinates
============ Working on FXR_12-FXR_74 ============
FXR_12→FXR_74
================ Building system =================
Traceback (most recent call last):
  File "/home/zhyx/PyAutoFEP/prepare_dual_topology.py", line 4559, in <module>
    build_data = prepare_complex_system(
  File "/home/zhyx/PyAutoFEP/os_util.py", line 558, in wrap_trace
    return f(*args, **kwargs)
  File "/home/zhyx/PyAutoFEP/prepare_dual_topology.py", line 680, in prepare_complex_system
    copyfiles = build_posres_and_chain_itp(
  File "/home/zhyx/PyAutoFEP/os_util.py", line 558, in wrap_trace
    return f(*args, **kwargs)
  File "/home/zhyx/PyAutoFEP/prepare_dual_topology.py", line 389, in build_posres_and_chain_itp
    fix_chain_restraint(this_filename, index_posre_data[prot_group][0], verbosity=verbosity)
  File "/home/zhyx/PyAutoFEP/prepare_dual_topology.py", line 174, in fix_chain_restraint
    restraint_data = os_util.read_file_to_buffer(restraint_file, die_on_error=True, return_as_list=True)
  File "/home/zhyx/PyAutoFEP/os_util.py", line 104, in read_file_to_buffer
    data_buffer = input_file.readlines()
  File "/home/zhyx/anaconda3/envs/FEP/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 47: invalid start byte
Perturbation BUG encountered while submitting generate_perturbation_map.py task Does anyone know how to solve this bug THANKS

**Comment by wenzeyu126553** [comment]
(FEP) zhyx@zhyx:~/PyAutoFEP$ conda list
# packages in environment at /home/zhyx/anaconda3/envs/FEP:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
alchemlyb                 0.6.0                    pypi_0    pypi
alsa-lib                  1.2.11               hd590300_1    conda-forge
attr                      2.5.1                h166bdaf_1    conda-forge
brotli                    1.1.0                hd590300_1    conda-forge
brotli-bin                1.1.0                hd590300_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
ca-certificates           2024.3.11            h06a4308_0    defaults
cairo                     1.18.0               h3faef2a_0    conda-forge
certifi                   2024.2.2         py38h06a4308_0    defaults
chardet                   5.2.0            py38h578d9bd_1    conda-forge
contourpy                 1.1.1            py38h7f3f72f_1    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
dbus                      1.13.18              hb2f20db_0    defaults
decorator                 5.1.1              pyhd3eb1b0_0    defaults
expat                     2.6.2                h59595ed_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_1    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.50.0           py38h01eb140_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
freetype-py               2.3.0              pyhd8ed1ab_0    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
glib                      2.80.0               hf2295e7_1    conda-forge
glib-tools                2.80.0               hde27a5a_1    conda-forge
graphite2                 1.3.14               h295c915_1    defaults
greenlet                  3.0.3            py38h17151c0_0    conda-forge
gst-plugins-base          1.22.9               hfa15dee_1    conda-forge
gstreamer                 1.22.9               h98fc4e7_1    conda-forge
harfbuzz                  8.3.0                h3d44ed6_0    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
importlib-resources       6.4.0              pyhd8ed1ab_0    conda-forge
importlib_resources       6.4.0              pyhd8ed1ab_0    conda-forge
joblib                    1.3.2                    pypi_0    pypi
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5            py38h7f3f72f_1    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
lame                      3.100                h7b6447c_0    defaults
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.38                 h1181459_1    defaults
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0           21_linux64_openblas    conda-forge
libboost                  1.84.0               h8013b2b_2    conda-forge
libboost-python           1.84.0           py38hae673b5_2    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcap                    2.69                 h0f662aa_0    conda-forge
libcblas                  3.9.0           21_linux64_openblas    conda-forge
libclang-cpp15            15.0.7          default_h127d8a8_5    conda-forge
libclang13                18.1.2          default_h5d6823c_1    conda-forge
libcups                   2.3.3                h4637d8d_4    conda-forge
libdeflate                1.20                 hd590300_0    conda-forge
libedit                   3.1.20230828         h5eee18b_0    defaults
libevent                  2.1.12               hdbd6064_1    defaults
libexpat                  2.6.2                h59595ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libflac                   1.4.3                h59595ed_0    conda-forge
libgcc-ng                 13.2.0               h807b86a_5    conda-forge
libgcrypt                 1.10.3               hd590300_0    conda-forge
libgfortran-ng            13.2.0               h69a702a_5    conda-forge
libgfortran5              13.2.0               ha4646dd_5    conda-forge
libglib                   2.80.0               hf2295e7_1    conda-forge
libgomp                   13.2.0               h807b86a_5    conda-forge
libgpg-error              1.48                 h71f35ed_0    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
liblapack                 3.9.0           21_linux64_openblas    conda-forge
libllvm15                 15.0.7               hb3ce162_4    conda-forge
libllvm18                 18.1.2               h2448989_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libogg                    1.3.5                h27cfd23_1    defaults
libopenblas               0.3.26          pthreads_h413a1c8_0    conda-forge
libopus                   1.3.1                h7b6447c_0    defaults
libpng                    1.6.43               h2797004_0    conda-forge
libpq                     16.2                 h33b98f1_1    conda-forge
libsndfile                1.2.2                hc60ed4a_1    conda-forge
libsqlite                 3.45.2               h2797004_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_5    conda-forge
libsystemd0               255                  h3516f8a_1    conda-forge
libtiff                   4.6.0                h1dd3fc0_3    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libvorbis                 1.3.7                h7b6447c_0    defaults
libwebp-base              1.3.2                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxkbcommon              1.7.0                h662e7e4_0    conda-forge
libxml2                   2.12.6               h232c23b_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
lz4-c                     1.9.4                h6a678d5_0    defaults
matplotlib                3.7.2            py38h06a4308_0    defaults
matplotlib-base           3.7.2            py38h1128e8f_0    defaults
mpg123                    1.32.4               h59595ed_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mysql-common              8.3.0                hf1915f5_4    conda-forge
mysql-libs                8.3.0                hca2cd23_4    conda-forge
ncurses                   6.4                  h6a678d5_0    defaults
networkx                  3.1                      pypi_0    pypi
nspr                      4.35                 h6a678d5_0    defaults
nss                       3.98                 h1d7d5a4_0    conda-forge
numpy                     1.24.4           py38h59b608b_0    conda-forge
openbabel                 3.1.1            py38h8a87c98_9    conda-forge
openjpeg                  2.5.2                h488ebb8_0    conda-forge
openssl                   3.2.1                hd590300_1    conda-forge
packaging                 24.0               pyhd8ed1ab_0    conda-forge
pandas                    2.0.3            py38h01efb38_1    conda-forge
pcre2                     10.43                hcad00b1_0    conda-forge
pillow                    10.2.0           py38ha43c96d_0    conda-forge
pip                       23.3.1           py38h06a4308_0    defaults
pixman                    0.43.2               h59595ed_0    conda-forge
ply                       3.11                     py38_0    defaults
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pulseaudio-client         17.0                 hb77b528_0    conda-forge
pycairo                   1.26.0           py38h1a1917b_0    conda-forge
pymbar                    3.0.5                    pypi_0    pypi
pyparsing                 3.0.9            py38h06a4308_0    defaults
pyqt                      5.15.10          py38h6a678d5_0    defaults
pyqt5-sip                 12.13.0          py38h5eee18b_0    defaults
python                    3.8.18          hd12c33a_1_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.8                      4_cp38    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
qt-main                   5.15.8              h112747c_20    conda-forge
rdkit                     2024.03.1        py38h924c20c_0    conda-forge
readline                  8.2                  h5eee18b_0    defaults
reportlab                 4.1.0            py38h01eb140_0    conda-forge
rlpycairo                 0.2.0              pyhd8ed1ab_0    conda-forge
scikit-learn              1.3.2                    pypi_0    pypi
setuptools                68.2.2           py38h06a4308_0    defaults
sip                       6.7.12           py38h6a678d5_0    defaults
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlalchemy                2.0.29           py38h01eb140_0    conda-forge
sqlite                    3.41.2               h5eee18b_0    defaults
threadpoolctl             3.4.0                    pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tomli                     2.0.1            py38h06a4308_0    defaults
tornado                   6.3.3            py38h5eee18b_0    defaults
typing-extensions         4.10.0               hd8ed1ab_0    conda-forge
typing_extensions         4.10.0             pyha770c72_0    conda-forge
unicodedata2              15.1.0           py38h01eb140_0    conda-forge
wheel                     0.41.2           py38h06a4308_0    defaults
xcb-util                  0.4.0                hd590300_1    conda-forge
xcb-util-image            0.4.0                h8ee46fc_1    conda-forge
xcb-util-keysyms          0.4.0                h8ee46fc_1    conda-forge
xcb-util-renderutil       0.3.9                hd590300_1    conda-forge
xcb-util-wm               0.4.1                h8ee46fc_1    conda-forge
xkeyboard-config          2.41                 hd590300_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.7                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xf86vidmodeproto     2.3.1             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.4.6                h5eee18b_0    defaults
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
