### ISSUE TITLE
Error while run analyze_results.py : IndexError: list index out of range

### ISSUE THREAD

**Issue by LiHui-CADD** [luancarvalhomartins/PyAutoFEP#143]
Everything is ok in my job. I can finish part of my jobs. But to some pairs, I have trouble in running analyze_results.py

My script is as follows:
analyze_results.py --input ./result3 --units kcal  --center_molecule=lig_6 --plot --read_from_xvg=never --no_checks

The error is just like this :

=================== STACK INFO ===================
  File "/public/home/hpc214038/software/PyAutoFEP-master/analyze_results.py", line 1596, in <module>
    msg_verbosity=os_util.verbosity_level.error)
  File "/public/home/hpc214038/software/PyAutoFEP-master/os_util.py", line 311, in local_print
    formatted_string = '\n{:=^50}\n{}{:=^50}\n'.format(' STACK INFO ', ''.join(traceback.format_stack()),
=================== STACK INFO ===================
[ERROR] The leg systems saved on your progress file are ['protein', 'water'] while the systems read from the input file ./result3 are []. Because you are using no_checks, I will try to go on.

=================== STACK INFO ===================
  File "/public/home/hpc214038/software/PyAutoFEP-master/analyze_results.py", line 1627, in <module>
    current_verbosity=arguments.verbose, msg_verbosity=os_util.verbosity_level.error)
  File "/public/home/hpc214038/software/PyAutoFEP-master/os_util.py", line 311, in local_print
    formatted_string = '\n{:=^50}\n{}{:=^50}\n'.format(' STACK INFO ', ''.join(traceback.format_stack()),
=================== STACK INFO ===================
[ERROR] Leg data corrupt. I read ./result3 as legs from your data. Because your are using no_checks, I am going on.
Traceback (most recent call last):
  File "/public/home/hpc214038/software/PyAutoFEP-master/analyze_results.py", line 1708, in <module>
    pairwise_ddg = [['pair', '{}_ddg'.format(found_systems[0]), '{}_err'.format(found_systems[0]),
IndexError: list index out of range

I cannot find any difference between jobs which success or failed.
So I need help please.

Looking forward for your reply!

Thank you

**Comment by LiHui-CADD** [comment]
I am trying to add the source pkl file before running in ./result3 , but the error remain

**Comment by LiHui-CADD** [comment]
And I cannot find difference in md directory, everything looks good
