### ISSUE TITLE
An Error of “prepare_dual_topology.py” in tutorial

### ISSUE THREAD

**Issue by jeromeRlon** [luancarvalhomartins/PyAutoFEP#36]
The following problem occurred while running the tutorial, and the previous steps were fine. 

I am confused by the KeyError: 37, can not find any information of it. 

(pyfep) jerome@ubuntu:~/Project/YXT/FEP-2/PyAutoFEP$ python3 generate_perturbation_map.py --map_type=star --map_bias=FXR_12 --input lig_data/*.mol
(pyfep) jerome@ubuntu:~/Project/YXT/FEP-2/PyAutoFEP$ python3 prepare_dual_topology.py --config_file=step2.ini
=============== mdp and run steps=================
         Complex                    Water          
        min01.mdp                 min01.mdp        
        min02.mdp                 min02.mdp        
        min03.mdp                  nve.mdp         
         nve.mdp                   nvt.mdp         
         nvt.mdp                   npt.mdp         
         npt.mdp                   md.mdp          
         md.mdp                       -            
==================================================
================= Input ligands ==================
   Name         Molecule            Topology      
  FXR_12   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c(Cl)c1[H] lig_data/FXR_12.itp
  FXR_74   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c(Br)c1[H] lig_data/FXR_74.itp
  FXR_76   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c([H])c1[H] lig_data/FXR_76.itp
  FXR_84   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c(F)c1[H] lig_data/FXR_84.itp
  FXR_85   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c(C([H])([H])[H])c1[H] lig_data/FXR_85.itp
  FXR_88   [H]c1c([H])c([H])c(S(=O)(=O)N2C([H])([H])C([H])([H])C3(C(=O)N(C([H])([H])c4c([H])c([H])c(C(=O)[O-])c([H])c4[H])c4c([H])c([H])c(Br)c([H])c43)C([H])([H])C2([H])[H])c(C(F)(F)F)c1[H] lig_data/FXR_88.itp
==================================================
=================== Poses read ===================
Name            File                
FXR_12          {'molecule': <rdkit.Chem.rdchem.Mol object at 0x7efcfc0d41c0>, 'topology': ['lig_data/FXR_12.itp']}
FXR_74          {'molecule': <rdkit.Chem.rdchem.Mol object at 0x7efcfc0d4170>, 'topology': ['lig_data/FXR_74.itp']}
FXR_76          {'molecule': <rdkit.Chem.rdchem.Mol object at 0x7efcfc0d4120>, 'topology': ['lig_data/FXR_76.itp']}
FXR_84          {'molecule': <rdkit.Chem.rdchem.Mol object at 0x7efcfc0d4030>, 'topology': ['lig_data/FXR_84.itp']}
FXR_85          {'molecule': <rdkit.Chem.rdchem.Mol object at 0x7efcfcd34e90>, 'topology': ['lig_data/FXR_85.itp']}
FXR_88          {'molecule': <rdkit.Chem.rdchem.Mol object at 0x7efcfc0d4210>, 'topology': ['lig_data/FXR_88.itp']}
=============== Superimposed poses ===============
Name            File                      Note           
FXR_12          {'molecule': <rdkit.Chem.rdchem.Mol object at 0x7efcfc0d41c0>, 'topology': ['lig_data/FXR_12.itp']} Read from saved state
FXR_74          {'molecule': <rdkit.Chem.rdchem.Mol object at 0x7efcfc0d4170>, 'topology': ['lig_data/FXR_74.itp']} Read from saved state
FXR_76          {'molecule': <rdkit.Chem.rdchem.Mol object at 0x7efcfc0d4120>, 'topology': ['lig_data/FXR_76.itp']} Read from saved state
FXR_84          {'molecule': <rdkit.Chem.rdchem.Mol object at 0x7efcfc0d4030>, 'topology': ['lig_data/FXR_84.itp']} Read from saved state
FXR_85          {'molecule': <rdkit.Chem.rdchem.Mol object at 0x7efcfcd34e90>, 'topology': ['lig_data/FXR_85.itp']} Read from saved state
FXR_88          {'molecule': <rdkit.Chem.rdchem.Mol object at 0x7efcfc0d4210>, 'topology': ['lig_data/FXR_88.itp']} Read from saved state
==================================================
================== Align poses ===================
Molecule FXR_12 aligned
Molecule FXR_74 aligned
Molecule FXR_76 aligned
Molecule FXR_84 aligned
Molecule FXR_85 aligned
Molecule FXR_88 aligned
================= Perturbations ==================
         State A                  State B         
         FXR_12                   FXR_74          
         FXR_12                   FXR_76          
         FXR_12                   FXR_84          
         FXR_12                   FXR_85          
         FXR_12                   FXR_88          
==================================================
================ Working on pairs ================
Perturbation Pose Coordinates
============ Working on FXR_12-FXR_74 ============
Traceback (most recent call last):
  File "prepare_dual_topology.py", line 3451, in <module>
    verbosity=arguments.verbose)
  File "/home/jerome/Project/YXT/FEP-2/PyAutoFEP/merge_topologies.py", line 728, in merge_topologies
    atom_b_charge = topology2.molecules[0].atoms_dict[b_idx].q_e
KeyError: 37

**Comment by luancarvalhomartins** [comment]
Just to let you know that I am a quite swamped these days and wasn't able to take a look at this issue yet, but I am doing that as soon as possible.

**Comment by luancarvalhomartins** [comment]
So far, I failed to reproduce this issue with the tutorial data or other ligands. Would you mind to run again with `-vvvv` and sending me the full log?
