### ISSUE TITLE
Can't kekulize mol

### ISSUE THREAD

**Issue by jiaming28** [luancarvalhomartins/PyAutoFEP#67]
core_mol = rdkit.Chem.RemoveHs(core_mol)
rdkit.Chem.rdchem.KekulizeException: Can't kekulize mol.  Unkekulized atoms: 9 10 11

I tried different rdkit version, 2020.9, 2022.03.1, 2022.09.1, but i still get the error.

**Comment by jiaming28** [comment]
python ../prepare_dual_topology.py --config_file=step2.ini
In this step to merge the topologies.

**Comment by luancarvalhomartins** [comment]
Thank you for your report and for your interest in PyAutoFEP.

Would you mind (a) posting the complete error message; and (b) sharing the input molecules? In case you rather not disclose your molecules here, feel free to reach me by email (luancarvalhomartins@gmail.com), so I can assist you.

**Comment by jiaming28** [comment]
Thank you for your reply. The complete error message as the picture show.
<img width="1687" alt="image" src="https://user-images.githubusercontent.com/55302988/203882873-cdd44228-c560-4415-8485-895a2d0cddf8.png">
And the molecule is showed below. 

@<TRIPOS>MOLECULE
mol59
56 60 1 0 0 
SMALL
USER_CHARGES


@<TRIPOS>ATOM
  1 C10    195.4080   288.0590    27.5950 C.3   1 Q83J  -0.3314139504
  2 C13    197.8640   288.7450    27.9260 C.2   1 Q83J   0.5369898782
  3 C15    197.4520   289.9140    28.8350 C.ar  1 Q83J  -0.0331443860
  4 C17    195.4570   281.7720    29.2590 C.ar  1 Q83J   0.1954820283
  5 C20    197.6680   291.2400    28.4750 C.ar  1 Q83J  -0.1737324110
  6 C21    196.8340   289.6390    30.0540 C.ar  1 Q83J  -0.1240842760
  7 C22    195.7750   282.6020    30.3240 C.ar  1 Q83J  -0.0929646244
  8 C24    196.4450   290.6710    30.8940 C.ar  1 Q83J  -0.1551462762
  9 C26    196.6700   291.9820    30.5210 C.ar  1 Q83J  -0.1248704854
 10 C01    196.8340   285.5250    27.3220 C.3   1 Q83J  -0.1238977060
 11 C04    197.2110   286.7480    26.5060 C.3   1 Q83J   0.1017757797
 12 C07    194.9370   286.8250    28.3680 C.3   1 Q83J   0.3527314581
 13 C12    194.5520   284.4740    27.6570 C.2   1 Q83J   0.3038736083
 14 C14    195.0220   283.1610    27.0460 C.2   1 Q83J   0.6432863265
 15 C16    195.1290   281.8910    27.8810 C.2   1 Q83J  -0.4218202705
 16 C18    194.9250   280.6270    27.4040 C.2   1 Q83J   0.0425703963
 17 C19    195.4180   280.3780    29.5160 C.ar  1 Q83J  -0.0414803465
 18 C23    197.2790   292.2640    29.3180 C.ar  1 Q83J  -0.1201790886
 19 C25    196.0270   282.0050    31.5480 C.ar  1 Q83J   0.2779368380
 20 C27    196.3240   284.7610    31.2120 C.3   1 Q83J  -0.0885558110
 21 C29    195.6880   279.8780    30.7800 C.ar  1 Q83J   0.2995055204
 22 C31    195.9500   277.8670    32.1790 C.2   1 Q83J  -0.1074726706
 23 H31    196.2577   278.3703    33.0837 H     1 Q83J   0.1429074383
 24 C33    195.4190   276.3220    30.7700 C.2   1 Q83J   0.1392140914
 25 H33    195.2187   275.3550    30.3328 H     1 Q83J   0.1318888140
 26 N02    195.4590   285.6100    27.7720 N.am  1 Q83J  -0.1803235150
 27 N05    196.8410   287.8700    27.3440 N.am  1 Q83J  -0.1997179819
 28 N08    195.1030   279.8230    28.3800 N.pl3 1 Q83J  -0.0889717903
 29 N28    195.9870   280.7040    31.7640 N.ar  1 Q83J  -0.6535315750
 30 N30    195.6520   278.4480    31.0350 N.pl3 1 Q83J   0.3676800382
 31 C32    195.8060   276.5490    32.0270 C.2   1 Q83J  -0.3180588974
 32 H32    195.9730   275.7993    32.7862 H     1 Q83J   0.1682477709
 33 N34    195.3240   277.4830    30.1560 N.2   1 Q83J  -0.5576773127
 34 O03    193.4360   284.5690    28.0390 O.2   1 Q83J  -0.5457642804
 35 O06    199.0090   288.5430    27.6990 O.2   1 Q83J  -0.5917524441
 36 O09    195.3090   283.1300    25.8990 O.2   1 Q83J  -0.5324987721
 37 O11    195.8330   283.9920    30.1470 O.3   1 Q83J  -0.1771647669
 38 H1     194.9310   288.1250    26.7530 H     1 Q83J   0.1462142806
 39 H2     195.2670   288.8580    28.1270 H     1 Q83J   0.1462142806
 40 H3     198.0780   291.4380    27.6640 H     1 Q83J   0.1554797343
 41 H4     196.6810   288.7570    30.3060 H     1 Q83J   0.1485463704
 42 H5     196.0360   290.4820    31.7070 H     1 Q83J   0.1497921829
 43 H6     196.4110   292.6750    31.0840 H     1 Q83J   0.1425694450
 44 H7     196.9410   284.7320    26.7740 H     1 Q83J   0.0984875746
 45 H8     197.4180   285.4660    28.0940 H     1 Q83J   0.0984875746
 46 H9     198.1650   286.7570    26.3320 H     1 Q83J   0.0515556838
 47 H10    196.7100   286.7670    25.6760 H     1 Q83J   0.0515556838
 48 H11    195.2470   286.8870    29.2850 H     1 Q83J  -0.0064713738
 49 H12    193.9680   286.7940    28.3560 H     1 Q83J  -0.0064713738
 50 H13    194.6970   280.3950    26.5320 H     1 Q83J   0.1753393276
 51 H14    197.4280   293.1480    29.0710 H     1 Q83J   0.1442766234
 52 H15    196.2420   282.5580    32.2640 H     1 Q83J   0.0805425632
 53 H16    196.5550   285.6470    30.8910 H     1 Q83J   0.0875289850
 54 H17    195.6440   284.8330    31.8990 H     1 Q83J   0.0875289850
 55 H18    197.1140   284.3350    31.5810 H     1 Q83J   0.0875289850
 56 H23    195.0210   278.9710    28.2930 H     1 Q83J   0.2414281201
@<TRIPOS>BOND
  1   1  12  1   
  2   1  27  1   
  3   1  38  1   
  4   1  39  1   
  5   2   3  1   
  6   2  27  am  
  7   2  35  2   
  8   3   5  ar  
  9   3   6  ar  
 10   4   7  ar  
 11   4  15  1   
 12   4  17  ar  
 13   5  18  ar  
 14   5  40  1   
 15   6   8  ar  
 16   6  41  1   
 17   7  19  ar  
 18   7  37  1   
 19   8   9  ar  
 20   8  42  1   
 21   9  18  ar  
 22   9  43  1   
 23  10  11  1   
 24  10  26  1   
 25  10  44  1   
 26  10  45  1   
 27  11  27  1   
 28  11  46  1   
 29  11  47  1   
 30  12  26  1   
 31  12  48  1   
 32  12  49  1   
 33  13  14  1   
 34  13  26  am  
 35  13  34  2   
 36  14  15  1   
 37  14  36  2   
 38  15  16  2   
 39  16  28  1   
 40  16  50  1   
 41  17  21  ar  
 42  17  28  1   
 43  18  51  1   
 44  19  29  ar  
 45  19  52  1   
 46  20  37  1   
 47  20  53  1   
 48  20  54  1   
 49  20  55  1   
 50  21  29  ar  
 51  21  30  1   
 52  22  23  1   
 53  22  30  1   
 54  22  31  2   
 55  24  25  1   
 56  24  31  1   
 57  24  33  2   
 58  28  56  1   
 59  30  33  1   
 60  31  32  1   
@<TRIPOS>SUBSTRUCTURE
  1 Q83J  37 GROUP 4 G **** 0

# MOE 2019.01 (io_trps.svl 2018.10)

**Comment by jiaming28** [comment]
@<TRIPOS>MOLECULE
mol60
59 63 1 0 0 
SMALL
USER_CHARGES


@<TRIPOS>ATOM
  1 C10    195.4080   288.0590    27.5950 C.3   1 Q83J  -0.3189949154
  2 C13    197.8640   288.7450    27.9260 C.2   1 Q83J   0.5395166078
  3 C15    197.4520   289.9140    28.8350 C.ar  1 Q83J  -0.0369713733
  4 C17    195.4570   281.7720    29.2590 C.ar  1 Q83J   0.1697025957
  5 C20    197.6680   291.2400    28.4750 C.ar  1 Q83J  -0.1727594048
  6 C21    196.8340   289.6390    30.0540 C.ar  1 Q83J  -0.1176007135
  7 C22    195.7750   282.6020    30.3240 C.ar  1 Q83J  -0.0904472964
  8 C24    196.4450   290.6710    30.8940 C.ar  1 Q83J  -0.1573352112
  9 C26    196.6700   291.9820    30.5210 C.ar  1 Q83J  -0.1257938505
 10 C01    196.8340   285.5250    27.3220 C.3   1 Q83J  -0.1153446812
 11 C04    197.2110   286.7480    26.5060 C.3   1 Q83J   0.0955416487
 12 C07    194.9370   286.8250    28.3680 C.3   1 Q83J   0.3458934054
 13 C12    194.5520   284.4740    27.6570 C.2   1 Q83J   0.3108118433
 14 C14    195.0220   283.1610    27.0460 C.2   1 Q83J   0.6328093125
 15 C16    195.1290   281.8910    27.8810 C.2   1 Q83J  -0.3929507657
 16 C18    194.9250   280.6270    27.4040 C.2   1 Q83J   0.0148599306
 17 C19    195.4180   280.3780    29.5160 C.ar  1 Q83J  -0.0597443386
 18 C23    197.2790   292.2640    29.3180 C.ar  1 Q83J  -0.1197558975
 19 C25    196.0270   282.0050    31.5480 C.ar  1 Q83J   0.2703915927
 20 C27    196.3240   284.7610    31.2120 C.3   1 Q83J  -0.1030702388
 21 C29    195.6880   279.8780    30.7800 C.ar  1 Q83J   0.3873350490
 22 C31    195.9500   277.8670    32.1790 C.2   1 Q83J  -0.0361637798
 23 C33    195.4190   276.3220    30.7700 C.2   1 Q83J   0.5006978014
 24 C35    195.1360   274.9520    30.1560 C.3   1 Q83J  -0.3447571375
 25 N02    195.4590   285.6100    27.7720 N.am  1 Q83J  -0.1847457545
 26 N05    196.8410   287.8700    27.3440 N.am  1 Q83J  -0.2013565723
 27 N08    195.1030   279.8230    28.3800 N.pl3 1 Q83J  -0.0676765885
 28 N28    195.9870   280.7040    31.7640 N.ar  1 Q83J  -0.6778210499
 29 N30    195.6520   278.4480    31.0350 N.pl3 1 Q83J   0.2428526816
 30 C32    195.8060   276.5490    32.0270 C.2   1 Q83J  -0.4774146396
 31 H32    195.9730   275.7993    32.7862 H     1 Q83J   0.1961297770
 32 N34    195.3240   277.4830    30.1560 N.2   1 Q83J  -0.6294870324
 33 O03    193.4360   284.5690    28.0390 O.2   1 Q83J  -0.5475230555
 34 O06    199.0090   288.5430    27.6990 O.2   1 Q83J  -0.5920158821
 35 O09    195.3090   283.1300    25.8990 O.2   1 Q83J  -0.5315465888
 36 O11    195.8330   283.9920    30.1470 O.3   1 Q83J  -0.1724289793
 37 H1     194.9310   288.1250    26.7530 H     1 Q83J   0.1425576938
 38 H2     195.2670   288.8580    28.1270 H     1 Q83J   0.1425576938
 39 H3     198.0780   291.4380    27.6640 H     1 Q83J   0.1552338801
 40 H4     196.6810   288.7570    30.3060 H     1 Q83J   0.1446440504
 41 H5     196.0360   290.4820    31.7070 H     1 Q83J   0.1506471216
 42 H6     196.4110   292.6750    31.0840 H     1 Q83J   0.1432068248
 43 H7     196.9410   284.7320    26.7740 H     1 Q83J   0.0965393923
 44 H8     197.4180   285.4660    28.0940 H     1 Q83J   0.0965393923
 45 H9     198.1650   286.7570    26.3320 H     1 Q83J   0.0527921017
 46 H10    196.7100   286.7670    25.6760 H     1 Q83J   0.0527921017
 47 H11    195.2470   286.8870    29.2850 H     1 Q83J  -0.0046271751
 48 H12    193.9680   286.7940    28.3560 H     1 Q83J  -0.0046271751
 49 H13    194.6970   280.3950    26.5320 H     1 Q83J   0.1797832167
 50 H14    197.4280   293.1480    29.0710 H     1 Q83J   0.1440914606
 51 H15    196.2420   282.5580    32.2640 H     1 Q83J   0.0868129515
 52 H16    196.5550   285.6470    30.8910 H     1 Q83J   0.0904984999
 53 H17    195.6440   284.8330    31.8990 H     1 Q83J   0.0904984999
 54 H18    197.1140   284.3350    31.5810 H     1 Q83J   0.0904984999
 55 H19    196.2120   278.3010    32.9590 H     1 Q83J   0.1391053084
 56 H20    195.6100   274.2690    30.6570 H     1 Q83J   0.1109431037
 57 H21    194.1830   274.7740    30.1880 H     1 Q83J   0.1109431037
 58 H22    195.4370   274.9430    29.2340 H     1 Q83J   0.1109431037
 59 H23    195.0210   278.9710    28.2930 H     1 Q83J   0.2447898513
@<TRIPOS>BOND
  1   1  12  1   
  2   1  26  1   
  3   1  37  1   
  4   1  38  1   
  5   2   3  1   
  6   2  26  am  
  7   2  34  2   
  8   3   5  ar  
  9   3   6  ar  
 10   4   7  ar  
 11   4  15  1   
 12   4  17  ar  
 13   5  18  ar  
 14   5  39  1   
 15   6   8  ar  
 16   6  40  1   
 17   7  19  ar  
 18   7  36  1   
 19   8   9  ar  
 20   8  41  1   
 21   9  18  ar  
 22   9  42  1   
 23  10  11  1   
 24  10  25  1   
 25  10  43  1   
 26  10  44  1   
 27  11  26  1   
 28  11  45  1   
 29  11  46  1   
 30  12  25  1   
 31  12  47  1   
 32  12  48  1   
 33  13  14  1   
 34  13  25  am  
 35  13  33  2   
 36  14  15  1   
 37  14  35  2   
 38  15  16  2   
 39  16  27  1   
 40  16  49  1   
 41  17  21  ar  
 42  17  27  1   
 43  18  50  1   
 44  19  28  ar  
 45  19  51  1   
 46  20  36  1   
 47  20  52  1   
 48  20  53  1   
 49  20  54  1   
 50  21  28  ar  
 51  21  29  1   
 52  22  29  1   
 53  22  30  2   
 54  22  55  1   
 55  23  24  1   
 56  23  30  1   
 57  23  32  2   
 58  24  56  1   
 59  24  57  1   
 60  24  58  1   
 61  27  59  1   
 62  29  32  1   
 63  30  31  1   
@<TRIPOS>SUBSTRUCTURE
  1 Q83J  36 GROUP 4 G **** 0

# MOE 2019.01 (io_trps.svl 2018.10)






@<TRIPOS>MOLECULE
mol61
59 63 1 0 0 
SMALL
USER_CHARGES


@<TRIPOS>ATOM
  1 C10    195.4080   288.0590    27.5950 C.3   1 Q83J  -0.3332706171
  2 C13    197.8640   288.7450    27.9260 C.2   1 Q83J   0.5261882148
  3 C15    197.4520   289.9140    28.8350 C.ar  1 Q83J  -0.0286069987
  4 C17    195.4570   281.7720    29.2590 C.ar  1 Q83J   0.1677293664
  5 C20    197.6680   291.2400    28.4750 C.ar  1 Q83J  -0.1718839581
  6 C21    196.8340   289.6390    30.0540 C.ar  1 Q83J  -0.1216339561
  7 C22    195.7750   282.6020    30.3240 C.ar  1 Q83J  -0.0626118669
  8 C24    196.4450   290.6710    30.8940 C.ar  1 Q83J  -0.1579818164
  9 C26    196.6700   291.9820    30.5210 C.ar  1 Q83J  -0.1213475327
 10 C01    196.8340   285.5250    27.3220 C.3   1 Q83J  -0.1120511754
 11 C04    197.2110   286.7480    26.5060 C.3   1 Q83J   0.0947382114
 12 C07    194.9370   286.8250    28.3680 C.3   1 Q83J   0.3603554417
 13 C12    194.5520   284.4740    27.6570 C.2   1 Q83J   0.3057820129
 14 C14    195.0220   283.1610    27.0460 C.2   1 Q83J   0.6394366959
 15 C16    195.1290   281.8910    27.8810 C.2   1 Q83J  -0.3984070918
 16 C18    194.9250   280.6270    27.4040 C.2   1 Q83J   0.0237596251
 17 C19    195.4180   280.3780    29.5160 C.ar  1 Q83J  -0.0871381294
 18 C23    197.2790   292.2640    29.3180 C.ar  1 Q83J  -0.1230284138
 19 C25    196.0270   282.0050    31.5480 C.ar  1 Q83J   0.2268826913
 20 C27    196.3240   284.7610    31.2120 C.3   1 Q83J  -0.0781708782
 21 C29    195.6880   279.8780    30.7800 C.ar  1 Q83J   0.4077288832
 22 C31    195.9500   277.8670    32.1790 C.2   1 Q83J  -0.2697364143
 23 C33    195.4190   276.3220    30.7700 C.2   1 Q83J  -0.0200924466
 24 H33    195.2187   275.3550    30.3328 H     1 Q83J   0.1614954620
 25 N02    195.4590   285.6100    27.7720 N.am  1 Q83J  -0.1914167553
 26 N05    196.8410   287.8700    27.3440 N.am  1 Q83J  -0.1916822097
 27 N08    195.1030   279.8230    28.3800 N.pl3 1 Q83J  -0.0643845759
 28 N28    195.9870   280.7040    31.7640 N.ar  1 Q83J  -0.6446919043
 29 N30    195.6520   278.4480    31.0350 N.pl3 1 Q83J   0.2561461808
 30 C32    195.8060   276.5490    32.0270 C.2   1 Q83J   0.2464112568
 31 C32    196.0268   275.5577    33.0309 C.3   1 Q83J  -0.4722158519
 32 H321   196.3359   276.0415    33.9574 H     1 Q83J   0.1266111925
 33 H322   196.8080   274.8733    32.7001 H     1 Q83J   0.1266111925
 34 H323   195.1049   275.0016    33.2013 H     1 Q83J   0.1266111925
 35 N34    195.3240   277.4830    30.1560 N.2   1 Q83J  -0.5394501645
 36 O03    193.4360   284.5690    28.0390 O.2   1 Q83J  -0.5461402101
 37 O06    199.0090   288.5430    27.6990 O.2   1 Q83J  -0.5896658839
 38 O09    195.3090   283.1300    25.8990 O.2   1 Q83J  -0.5317169187
 39 O11    195.8330   283.9920    30.1470 O.3   1 Q83J  -0.1824193735
 40 H1     194.9310   288.1250    26.7530 H     1 Q83J   0.1458061195
 41 H2     195.2670   288.8580    28.1270 H     1 Q83J   0.1458061195
 42 H3     198.0780   291.4380    27.6640 H     1 Q83J   0.1550626566
 43 H4     196.6810   288.7570    30.3060 H     1 Q83J   0.1474570398
 44 H5     196.0360   290.4820    31.7070 H     1 Q83J   0.1502681119
 45 H6     196.4110   292.6750    31.0840 H     1 Q83J   0.1412580764
 46 H7     196.9410   284.7320    26.7740 H     1 Q83J   0.0948657820
 47 H8     197.4180   285.4660    28.0940 H     1 Q83J   0.0948657820
 48 H9     198.1650   286.7570    26.3320 H     1 Q83J   0.0533167096
 49 H10    196.7100   286.7670    25.6760 H     1 Q83J   0.0533167096
 50 H11    195.2470   286.8870    29.2850 H     1 Q83J  -0.0083240467
 51 H12    193.9680   286.7940    28.3560 H     1 Q83J  -0.0083240467
 52 H13    194.6970   280.3950    26.5320 H     1 Q83J   0.1762389866
 53 H14    197.4280   293.1480    29.0710 H     1 Q83J   0.1444190756
 54 H15    196.2420   282.5580    32.2640 H     1 Q83J   0.0938031649
 55 H16    196.5550   285.6470    30.8910 H     1 Q83J   0.0848046260
 56 H17    195.6440   284.8330    31.8990 H     1 Q83J   0.0848046260
 57 H18    197.1140   284.3350    31.5810 H     1 Q83J   0.0848046260
 58 H19    196.2120   278.3010    32.9590 H     1 Q83J   0.1677298890
 59 H23    195.0210   278.9710    28.2930 H     1 Q83J   0.2412775156
@<TRIPOS>BOND
  1   1  12  1   
  2   1  26  1   
  3   1  40  1   
  4   1  41  1   
  5   2   3  1   
  6   2  26  am  
  7   2  37  2   
  8   3   5  ar  
  9   3   6  ar  
 10   4   7  ar  
 11   4  15  1   
 12   4  17  ar  
 13   5  18  ar  
 14   5  42  1   
 15   6   8  ar  
 16   6  43  1   
 17   7  19  ar  
 18   7  39  1   
 19   8   9  ar  
 20   8  44  1   
 21   9  18  ar  
 22   9  45  1   
 23  10  11  1   
 24  10  25  1   
 25  10  46  1   
 26  10  47  1   
 27  11  26  1   
 28  11  48  1   
 29  11  49  1   
 30  12  25  1   
 31  12  50  1   
 32  12  51  1   
 33  13  14  1   
 34  13  25  am  
 35  13  36  2   
 36  14  15  1   
 37  14  38  2   
 38  15  16  2   
 39  16  27  1   
 40  16  52  1   
 41  17  21  ar  
 42  17  27  1   
 43  18  53  1   
 44  19  28  ar  
 45  19  54  1   
 46  20  39  1   
 47  20  55  1   
 48  20  56  1   
 49  20  57  1   
 50  21  28  ar  
 51  21  29  1   
 52  22  29  1   
 53  22  30  2   
 54  22  58  1   
 55  23  24  1   
 56  23  30  1   
 57  23  35  2   
 58  27  59  1   
 59  29  35  1   
 60  30  31  1   
 61  31  32  1   
 62  31  33  1   
 63  31  34  1   
@<TRIPOS>SUBSTRUCTURE
  1 Q83J  39 GROUP 4 G **** 0

# MOE 2019.01 (io_trps.svl 2018.10)

**Comment by jiaming28** [comment]
python ../../prepare_dual_topology.py --config_file=step2.ini
=============== mdp and run steps=================
         Complex                    Water
        min01.mdp                 min01.mdp
        min02.mdp                 min02.mdp
        min03.mdp                  nve.mdp
         nve.mdp                   nvt.mdp
         nvt.mdp                   npt.mdp
         npt.mdp                   md.mdp
         md.mdp                       -
==================================================
================= Input ligands ==================
   Name         Molecule            Topology
  mol59    [H]c1nn(-c2nc([H])c(OC([H])([H])[H])c3c(C(=O)C(=O)N4C([H])([H])C([H])([H])N(C(=O)c5c([H])c([H])c([H])c([H])c5[H])C([H])([H])C4([H])[H])c([H])n([H])c23)c([H])c1[H] lig_data/mol59.itp
  mol60    [H]c1nc(-n2nc(C([H])([H])[H])c([H])c2[H])c2c(c1OC([H])([H])[H])c(C(=O)C(=O)N1C([H])([H])C([H])([H])N(C(=O)c3c([H])c([H])c([H])c([H])c3[H])C([H])([H])C1([H])[H])c([H])n2[H] lig_data/mol60.itp
  mol61    [H]c1nn(-c2nc([H])c(OC([H])([H])[H])c3c(C(=O)C(=O)N4C([H])([H])C([H])([H])N(C(=O)c5c([H])c([H])c([H])c([H])c5[H])C([H])([H])C4([H])[H])c([H])n([H])c23)c([H])c1C([H])([H])[H] lig_data/mol61.itp
  mol62    [H]c1nn(-c2nc([H])c(OC([H])([H])[H])c3c(C(=O)C(=O)N4C([H])([H])C([H])([H])N(C(=O)c5c([H])c([H])c([H])c([H])c5[H])C([H])([H])C4([H])[H])c([H])n([H])c23)c(C([H])([H])[H])c1[H] lig_data/mol62.itp
==================================================
=================== Poses read ===================
Name            File                 Details
mol59           {'molecule': <rdkit.Chem.PropertyMol.PropertyMol object at 0x147709591ab0>, 'topology': ['lig_data/mol59.itp']}
mol60           {'molecule': <rdkit.Chem.PropertyMol.PropertyMol object at 0x14770517b370>, 'topology': ['lig_data/mol60.itp']}
mol61           {'molecule': <rdkit.Chem.PropertyMol.PropertyMol object at 0x1477094ae770>, 'topology': ['lig_data/mol61.itp']}
mol62           {'molecule': <rdkit.Chem.PropertyMol.PropertyMol object at 0x1477094ae930>, 'topology': ['lig_data/mol62.itp']}
=============== Superimposed poses ===============
Name            File                      Note
mol59           {'molecule': <rdkit.Chem.PropertyMol.PropertyMol object at 0x147709591ab0>, 'topology': ['lig_data/mol59.itp']} Read from saved state
Traceback (most recent call last):
  File "../../prepare_dual_topology.py", line 3738, in <module>
    verbosity=arguments.verbose, **arguments.poses_advanced_options)
  File "../../prepare_dual_topology.py", line 3157, in align_ligands
    save_state=save_state, verbosity=verbosity, **kwargs)
  File "/home/guanjiaming/projects/instance_fep/PyAutoFEP/docking_readers/superimpose_loader.py", line 127, in superimpose_poses
    atom_map=this_atommap, **kwargs)
  File "/home/guanjiaming/projects/instance_fep/PyAutoFEP/os_util.py", line 535, in wrap_trace
    return f(*args, **kwargs)
  File "/home/guanjiaming/projects/instance_fep/PyAutoFEP/merge_topologies.py", line 301, in constrained_embed_shapeselect
    core_mol = rdkit.Chem.RemoveHs(core_mol)
rdkit.Chem.rdchem.KekulizeException: Can't kekulize mol.  Unkekulized atoms: 3 6 14 15 16 18 20 25 26

**Comment by luancarvalhomartins** [comment]
Thank you very much for your detailed data. 

So the problem happened during sanitization of the common core between `mol60` and your reference pose during superimposition. RDKit readed and kekulized your input molecules correctly and the MCS should encompass the pyrrolopyridine (which seems to be the ring that RDKIT failed to kekulize).

Would mind posting the output with debug level messages (ie, with `-vvvv`)? Also, which is your `poses_reference_pose_superimpose`?

**Comment by luancarvalhomartins** [comment]
Just to note that I did some tests and committed code ([0a59763](https://github.com/luancarvalhomartins/PyAutoFEP/commit/0a5976308a62f646afe9b5a89ddee9f715364c30)) that turn the sanitization error into a warning at that specific point. Would you mind giving this new commit a try?

**Comment by jiaming28** [comment]
Thank you very much for your patience in answering, and sorry for the late reply. I tried your new code (0a59763) and it doesn't report an error about 'kekulize', but it seems to be another error.

================= Input ligands ==================
   Name         Molecule            Topology
Tankyrase-34 [H]c1nc([H])c2c(c1[H])n([C@]1([H])C([H])([H])C([H])([H])[C@@]([H])(N3C(=O)OC(C([H])([H])[H])(C([H])([H])[H])[C@]3([H])c3c([H])c([H])c([H])c([H])c3[H])C([H])([H])C1([H])[H])c(=O)n2[H] lig_data/Tankyrase-34.itp
Tankyrase-35 [H]c1nc2c(c([H])c1[H])n([C@]1([H])C([H])([H])C([H])([H])[C@@]([H])(N3C(=O)OC(C([H])([H])[H])(C([H])([H])[H])[C@]3([H])c3c([H])c([H])c([H])c([H])c3[H])C([H])([H])C1([H])[H])c(=O)n2[H] lig_data/Tankyrase-35.itp
Tankyrase-46 [H]c1nc2c(c([H])c1[H])n([H])c(=O)n2[C@]1([H])C([H])([H])C([H])([H])[C@@]([H])(N2C(=O)OC(C([H])([H])[H])(C([H])([H])[H])[C@]2([H])c2c([H])c([H])c([H])c([H])c2[H])C([H])([H])C1([H])[H] lig_data/Tankyrase-46.itp
Tankyrase-48 [H]c1nc([H])c2c(c1[H])n([H])c(=O)n2[C@]1([H])C([H])([H])C([H])([H])[C@@]([H])(N2C(=O)OC(C([H])([H])[H])(C([H])([H])[H])[C@]2([H])c2c([H])c([H])c([H])c([H])c2[H])C([H])([H])C1([H])[H] lig_data/Tankyrase-48.itp
==================================================
=================== Poses read ===================
Name            File                 Details
Tankyrase-34    {'molecule': <rdkit.Chem.PropertyMol.PropertyMol object at 0x152bc7454370>, 'topology': ['lig_data/Tankyrase-34.itp']}
Tankyrase-35    {'molecule': <rdkit.Chem.PropertyMol.PropertyMol object at 0x152bc745b4b0>, 'topology': ['lig_data/Tankyrase-35.itp']}
Tankyrase-46    {'molecule': <rdkit.Chem.PropertyMol.PropertyMol object at 0x152bc745b170>, 'topology': ['lig_data/Tankyrase-46.itp']}
Tankyrase-48    {'molecule': <rdkit.Chem.PropertyMol.PropertyMol object at 0x152bcd588df0>, 'topology': ['lig_data/Tankyrase-48.itp']}
=============== Superimposed poses ===============
Name            File                      Note
Tankyrase-34    {'molecule': <rdkit.Chem.PropertyMol.PropertyMol object at 0x152bc7454370>, 'topology': ['lig_data/Tankyrase-34.itp']} Read from saved state
Tankyrase-35    {'molecule': <rdkit.Chem.PropertyMol.PropertyMol object at 0x152bc745b4b0>, 'topology': ['lig_data/Tankyrase-35.itp']}
Tankyrase-46    {'molecule': <rdkit.Chem.PropertyMol.PropertyMol object at 0x152bc745b170>, 'topology': ['lig_data/Tankyrase-46.itp']}
Tankyrase-48    {'molecule': <rdkit.Chem.PropertyMol.PropertyMol object at 0x152bcd588df0>, 'topology': ['lig_data/Tankyrase-48.itp']}
==================================================
================== Align poses ===================
Molecule Tankyrase-34 aligned
Molecule Tankyrase-35 aligned
Molecule Tankyrase-46 aligned
Molecule Tankyrase-48 aligned
================= Perturbations ==================
         State A                  State B
      Tankyrase-34             Tankyrase-35
      Tankyrase-34             Tankyrase-46
      Tankyrase-34             Tankyrase-48
==================================================
================ Working on pairs ================
Perturbation Pose Coordinates
====== Working on Tankyrase-34-Tankyrase-35 ======
Traceback (most recent call last):
  File "../../prepare_dual_topology.py", line 4062, in <module>
    verbosity=arguments.verbose)
  File "/home/guanjiaming/projects/instance_fep/PyAutoFEP/merge_topologies.py", line 1077, in merge_topologies
    delta_charge=delta_charge)
TypeError: __init__() got an unexpected keyword argument 'atom_map'

**Comment by jiaming28** [comment]
But you suggested that the problem happened during sanitization of the common core between molecule and my reference pose during superimposition. Because my molecule was processed, I used the parameters of pose_loader = generic, poses_input = lig_data/*.mol2. It seems to temporarily fix the issue.

**Comment by luancarvalhomartins** [comment]
Sorry, I could not reproduce the `TypeError: __init__() got an unexpected keyword argument 'atom_map'` error. MergedTopologies has an atom_map argument since https://github.com/luancarvalhomartins/PyAutoFEP/commit/c6e427c318c695f5d4a5d0f375e17b0bb16ced68 :
 https://github.com/luancarvalhomartins/PyAutoFEP/blob/0a5976308a62f646afe9b5a89ddee9f715364c30/all_classes.py#L2617

- Would you mind checking that your `all_classes.py` is updated? If it isn't, updating (eg, `git pull`) should fix the issue. 
- Are you keeping your progress files (eg, `progress.pkl`) from an older version of the code? In case you are, would you mind removing the progress file and retrying?

**Comment by luancarvalhomartins** [comment]
It seems that [0a59763](https://github.com/luancarvalhomartins/PyAutoFEP/commit/0a5976308a62f646afe9b5a89ddee9f715364c30) fixes the original bug, so I am marking this issue closed. Feel free to comment here or fill another one for the `TypeError: __init__() got an unexpected keyword argument 'atom_map'` issue.
