### ISSUE TITLE
output_scripttype = pbs not working 

### ISSUE THREAD

**Issue by luancarvalhomartins** [luancarvalhomartins/PyAutoFEP#7]
PyAutoFEP dies with an error when `output_scripttype = pbs` is used.

```
================ Working on pairs ================
Perturbation Pose Coordinates
Traceback (most recent call last):
  File "prepare_dual_topology.py", line 3189, in <module>
    verbosity=arguments.verbose)
  File "prepare_dual_topology.py", line 675, in prepare_output_scripts_data
    temp_str = template_section['header']
  File "/home/luancarvalho/anaconda3/envs/PyAutoFEP_testrepo/lib/python3.7/configparser.py", line 1251, in __getitem__
    raise KeyError(key)
KeyError: 'header'
```

**Comment by luancarvalhomartins** [comment]
Fixed by 24f45dea102b5971f78f735cc9eec21ff8e4cb2f
