### ISSUE TITLE
prepare dual topology: utf-8 coded can't decode: Error in pickling?

### ISSUE THREAD

**Issue by Fplanas92** [luancarvalhomartins/PyAutoFEP#81]
When running prepare dual topology I get the error:

Traceback (most recent call last):
  File "/data/users/fepd/PyAutoFEP/prepare_dual_topology.py", line 3916, in <module>
    perturbation_map = process_perturbation_map(arguments.perturbation_map, verbosity=arguments.verbose)
  File "/data/users/fepd/PyAutoFEP/prepare_dual_topology.py", line 3152, in process_perturbation_map
    file_data = os_util.read_file_to_buffer(file_name, die_on_error=False, return_as_list=False,
  File "/data/users/fepd/PyAutoFEP/os_util.py", line 104, in read_file_to_buffer
    data_buffer = input_file.read()
  File "/data/users/fepd/miniconda3/envs/Gromacs_3.8/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

I have run using Python 3.8 and 3.10, and both return the same
I would appreciate any input!

Thanks :)

**Comment by luancarvalhomartins** [comment]
Thank you for you comment.

Are you passing a pickle file as the `perturbation_map`? Doing that is not supposed to work, as it would require to manually pickle a perturbation map. How did you prepare your perturbation map? In case you are using `generate_perturbation_map.py`, use the `progress_file` instead.  In case you did it another way, maybe generating a text file is easier.

LMK if it's something else.
