### ISSUE TITLE
GROMACS jobs appear to complete but analyze_results.py fails

### ISSUE THREAD

**Issue by Moricant** [luancarvalhomartins/PyAutoFEP#88]
Hi, I've run into a problem where the GROMACS jobs all appear to complete successfully but analyze_results.py fails:

(PyAutoFEP_Output) [obarker@ccrcb-140996 Output]$ analyze_results.py --input ATR_FEP_6_20230517.tgz --output_uncompress_directory ATR_FEP_6_20230517  --center_molecule=Benchmark
All available analysis will be run
================== Pairwise ΔΔG ==================
         Perturbation           protein    water
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/work/obarker/anaconda3/envs/PyAutoFEP_Output/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/work/obarker/anaconda3/envs/PyAutoFEP_Output/lib/python3.11/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/apps/PyAutoFEP/os_util.py", line 381, in wrapper_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/work/apps/PyAutoFEP/analyze_results.py", line 903, in analyze_perturbation
    ddg_data = convergence_analysis(u_nk, estimators=estimators_data, convergence_step=convergence_analysis_step,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/apps/PyAutoFEP/analyze_results.py", line 195, in convergence_analysis
    reversed_data = reversed_data.append(pandas.DataFrame(block_array, columns=columns).set_index(index))
                    ^^^^^^^^^^^^^^^^^^^^
  File "/work/obarker/anaconda3/envs/PyAutoFEP_Output/lib/python3.11/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'append'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/work/apps/PyAutoFEP/analyze_results.py", line 1709, in <module>
    ddg_data_result = os_util.starmap_unpack(analyze_perturbation, threads,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/apps/PyAutoFEP/os_util.py", line 402, in starmap_unpack
    return pool.starmap(wrapper_fn, list(assembled_args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/obarker/anaconda3/envs/PyAutoFEP_Output/lib/python3.11/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/obarker/anaconda3/envs/PyAutoFEP_Output/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
AttributeError: 'DataFrame' object has no attribute 'append'

There is one error listed in the slurm output for the pack.sh job: 

$ more slurm-11621963.out
tar: */water/md/lambda*/lambda.xtc: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors

**Comment by Moricant** [comment]
Oh, and it's using commit 11da24d

**Comment by Moricant** [comment]
Ah, I see the problem. DataFrame.append() was removed in pandas 2.0. Had a stab at replacing the instances of append on lines 195 and 578 with concat as suggested but ended up with more errors:

All available analysis will be run
================== Pairwise ΔΔG ==================
         Perturbation           protein    water
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/work/obarker/anaconda3/envs/PyAutoFEP/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/work/obarker/anaconda3/envs/PyAutoFEP/lib/python3.11/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/apps/PyAutoFEP/os_util.py", line 381, in wrapper_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/work/apps/PyAutoFEP/analyze_results.py", line 903, in analyze_perturbation
    ddg_data = convergence_analysis(u_nk, estimators=estimators_data, convergence_step=convergence_analysis_step,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/apps/PyAutoFEP/analyze_results.py", line 195, in convergence_analysis
    reversed_data = reversed_data.concat(pandas.DataFrame(block_array, columns=columns).set_index(index))
                    ^^^^^^^^^^^^^^^^^^^^
  File "/work/obarker/anaconda3/envs/PyAutoFEP/lib/python3.11/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'concat'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/work/apps/PyAutoFEP/analyze_results.py", line 1709, in <module>
    ddg_data_result = os_util.starmap_unpack(analyze_perturbation, threads,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/apps/PyAutoFEP/os_util.py", line 402, in starmap_unpack
    return pool.starmap(wrapper_fn, list(assembled_args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/obarker/anaconda3/envs/PyAutoFEP/lib/python3.11/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/obarker/anaconda3/envs/PyAutoFEP/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value


For now, I've worked around by rolling back to pandas 1.5.3 and suppressing the warnings.

**Comment by luancarvalhomartins** [comment]
Thank you for your bug report. Indeed, `DataFrame.append` was removed in `pandas-2.0`. I will update the code to use `concat` instead.
